'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tiers=[['Bronze',0],['Silver',1000],['Gold',1200],['Platinum',1400],['Diamond',1600],['Master',1800],['Grandmaster',2000]];
let rows=[],cursor=null,selected=new URL(location.href).searchParams.get('player'),busy=false,lookupSequence=0,ladderSequence=0;
const own=location.hostname==='game.exudizmono.com';const api=async path=>{const r=await fetch((own?'/backend':'/api')+path,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(15000)});const b=await r.json();if(!r.ok)throw Error(b.error||'Could not load stats.');return b;};
const percent=p=>p.total?100*p.wins/p.total:0;
function render(){const tier=$('tier').value,sort=$('sort').value;const list=rows.filter(p=>tier==='all'||p.tier===tier).slice().sort((a,b)=>sort==='winRate'?percent(b)-percent(a):sort==='total'?b.total-a.total:((a.rank??Infinity)-(b.rank??Infinity)));
 $('rows').innerHTML=list.length?list.map(p=>`<tr><td class="rank-number">${p.rank??'—'}</td><td><button class="player-button" data-player="${esc(p.public_id)}">${esc(p.username||p.public_id)}</button></td><td><span class="badge">${esc(p.tier)}</span></td><td class="rating">${p.elo??'—'}</td><td>${percent(p).toFixed(1)}%</td><td>${p.total}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No completed games match these filters yet.</td></tr>';
 $('resultCount').textContent=`${list.length} displayed · ranks calculated across the full ladder`;$('more').hidden=!cursor;$('more').disabled=busy;
 const p=rows.find(p=>p.public_id===selected)||rows[0];$('profile').innerHTML=p?`<span class="eyebrow">${esc($('mode').selectedOptions[0]?.textContent)}</span><h3>${esc(p.username||p.public_id)}</h3><p>Rank ${p.rank??'Unrated'} · ${esc(p.tier)}</p><div class="profile-rating">${p.elo??'—'} <small>skill rating</small></div><p>${p.ratedGames} rated games · ${p.wins} wins · ${p.losses} losses</p><p class="profile-note">${p.provisional?'Complete 10 rated matches in this mode for placement.':'Placement complete.'}</p>`:'<h3>No player selected</h3><p>Real players appear after recorded matches. There are no demo accounts.</p>';
}
async function ladder(append=false){const request=++ladderSequence;busy=true;$('connect').disabled=true;try{const params=new URLSearchParams({mode:$('mode').value||'all',variant:$('variant').value||'all',q:$('search').value.trim(),tier:$('tier').value,sort:$('sort').value,cursor:append?cursor||'0':'0'});const b=await api('/leaderboard/recorded?'+params);if(request!==ladderSequence)return;rows=append?[...rows,...b.players]:b.players;cursor=b.nextCursor;$('playersCount').textContent=b.totalPlayers;$('average').textContent=b.averageRating??'—';$('leader').textContent=b.leader?.username||b.leader?.public_id||'—';$('scope').textContent=$('mode').selectedOptions[0]?.textContent||'All multiplayer';$('sourceLabel').textContent='LIVE · EXUDIZMONO';$('sourceMessage').textContent=b.totalPlayers?'Ranks from your server’s recorded games.':'No completed public matches recorded yet. New results appear here automatically.';render();}catch(e){if(request===ladderSequence){$('sourceLabel').textContent='UNAVAILABLE';$('sourceMessage').textContent=e.message;}}finally{if(request===ladderSequence){busy=false;$('connect').disabled=false;}}}
async function profile(id){const seq=++lookupSequence;selected=id;$('player-id').value=id;$('lookup-status').textContent='Loading…';try{const [p,h]=await Promise.all([api('/public/player/'+encodeURIComponent(id)),api('/public/player/'+encodeURIComponent(id)+'/games')]);if(seq!==lookupSequence)return;let totals={wins:0,losses:0,total:0};function sum(o){if(o&&typeof o==='object'){if('wins'in o&&'total'in o){for(const k of Object.keys(totals))totals[k]+=Number(o[k]||0);}else for(const v of Object.values(o))sum(v);}}sum(p.stats);const ratings=p.ratings||[];$('real-player').innerHTML=`<div class="real-header"><div><h3>${esc(p.username||p.publicId)}</h3><p>Public ID: ${esc(p.publicId)}</p></div><p>${totals.total} recorded games · ${totals.wins} wins · ${totals.losses} losses</p></div><div class="real-modes">${ratings.length?ratings.map(r=>`<div class="real-mode"><b>${esc(r.label)}</b><strong>${r.elo} skill rating</strong><small>Rank ${r.rank??'—'} · ${esc(r.tier)} · ${r.ratedGames} rated matches</small></div>`).join(''):'<p>Unrated — complete eligible public games to earn a mode rating.</p>'}</div><h3 class="history-title">Match history</h3>${h.results.length?'<div class="table-scroll"><table><tr><th>Played</th><th>Map</th><th>Mode / variant</th><th>Result</th></tr>'+h.results.map(g=>`<tr><td>${esc(new Date(g.start).toLocaleDateString())}</td><td>${esc(g.map)}</td><td>${esc(g.modeKey||g.mode)} · ${esc(g.variant)}</td><td>${esc(g.result)}</td></tr>`).join('')+'</table></div>':'<p>No recorded matches yet.</p>'}${h.nextCursor?'<button id="history-more">Load older matches</button>':''}`;$('lookup-status').textContent='Loaded from Exudizmono. History shows up to 50 matches.';const url=new URL(location.href);url.searchParams.set('player',id);url.hash='profile-section';history.replaceState(null,'',url);if(h.nextCursor){document.getElementById('history-more').onclick=async e=>{try{const next=await api('/public/player/'+encodeURIComponent(id)+'/games?cursor='+h.nextCursor);e.target.insertAdjacentHTML('beforebegin',next.results.map(g=>`<p>${esc(g.start)} · ${esc(g.map)} · ${esc(g.modeKey)} · ${esc(g.result)}</p>`).join(''));h.nextCursor=next.nextCursor;if(!h.nextCursor)e.target.remove();}catch(e){$('lookup-status').textContent=e.message;}};}render();}catch(e){if(seq===lookupSequence){$('real-player').innerHTML='';$('lookup-status').textContent=e.message;}}}
$('rankCards').innerHTML=tiers.map(([name,min],i)=>`<div class="rank-card"><div class="rank-symbol">${i+1}</div><b>${name}</b><small>${min}${tiers[i+1]?'–'+(tiers[i+1][1]-1):'+'} rating</small></div>`).join('');for(const name of ['Unrated','Provisional',...tiers.map(t=>t[0])]){const opt=document.createElement('option');opt.value=name;opt.textContent=name;$('tier').append(opt);}
$('lookup-form').onsubmit=e=>{e.preventDefault();profile($('player-id').value.trim());};$('connect').onclick=()=>ladder();$('more').onclick=()=>ladder(true);$('rows').onclick=e=>{const b=e.target.closest('[data-player]');if(b)profile(b.dataset.player);};$('mode').onchange=()=>{rows=[];ladder();};$('variant').onchange=()=>ladder();let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>ladder(),250);};$('tier').onchange=()=>ladder();$('sort').onchange=()=>ladder();
(async()=>{try{const catalog=await api('/leaderboard/modes');for(const m of catalog.modes){const o=document.createElement('option');o.value=m.id;o.textContent=m.label;$('mode').append(o);}for(const v of catalog.variants.filter(v=>v.id!=='all')){const o=document.createElement('option');o.value=v.id;o.textContent=v.label;$('variant').append(o);}await ladder();if(selected)await profile(selected);else if(own){const auth=await fetch('/backend/auth/refresh',{method:'POST'});const session=await auth.json();const me=await(await fetch('/backend/users/@me',{headers:{Authorization:'Bearer '+session.jwt}})).json();$('identity').textContent='Your player ID: '+me.player.publicId;await profile(me.player.publicId);}}catch(e){$('sourceMessage').textContent=e.message;}})();
